name: 'Quote Card'
slug: 'quote_card'
category: 'Editorial'
component: 'Settings'
package_name: 'riga-tool-quote-card'
image: 'https://i.ibb.co/JkdZrXj/Blueprint-0.jpg'
url: 'http://localhost:5174/quote-card'
