name: 'Quote Card'
slug: 'quote_card'
category: 'Editorial'
package_name: 'riga-editor-tool-quote-card'
image: 'https://i.ibb.co/JkdZrXj/Blueprint-0.jpg'
url: 'https://nice-bush-008d43c03.3.azurestaticapps.net/'
output:
  type: 'iframe'
  code: '<iframe src="https://nice-bush-008d43c03.3.azurestaticapps.net/?tiid={tiid}" width="100%" height="100%" frameborder="0" title="tool-ui"></iframe>'
  tiid: true
  panel_title: 'Copy output code'
  panel_description: 'This is your iframe embed code'
settings:
  quote_text: 'Hello'
  quote_symbol: '&#10078;'
  quote_text_size: 3
  quote_text_color: '#666666'
  quote_symbol_color: '#f0f0f0'
  quote_background_color: '#fcfcfc'
