name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    env:
      VITE_RIGA_API_ENDPOINT: ${{ secrets.VITE_RIGA_API_ENDPOINT }}
    steps:
      - uses: actions/checkout@v3
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_BUSH_008D43C03 }}
          action: "upload"
          app_location: '/'
          output_location: 'build/static'
